add_library(libScePosixForWebKit SHARED EXCLUDE_FROM_ALL Export.cpp File.cpp Resolver.cpp)
target_include_directories(libScePosixForWebKit PRIVATE ${LIBS_INCLUDE_DIR})
target_link_libraries(libScePosixForWebKit PRIVATE libkernel libc)
if(WIN32)
    target_link_libraries(libScePosixForWebKit PRIVATE ws2_32)
endif()
configure_windows_unwind(libScePosixForWebKit)

if(BUILD_TESTING)
    add_test_executable(guest_resolver_tests ${LIBS_INCLUDE_DIR}/tests/GuestResolver.cpp)
    target_include_directories(guest_resolver_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_resolver_tests PRIVATE libScePosixForWebKit)
    add_test(NAME guest_resolver COMMAND guest_resolver_tests)
    if(WIN32)
        set_tests_properties(guest_resolver PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libScePosixForWebKit>")
    endif()
    add_test_executable(guest_posix_file_tests ${LIBS_INCLUDE_DIR}/tests/GuestPosixFile.cpp)
    target_include_directories(guest_posix_file_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_posix_file_tests PRIVATE libScePosixForWebKit libkernel libc)
    configure_windows_unwind(guest_posix_file_tests)
    add_test(NAME guest_posix_file COMMAND guest_posix_file_tests)
    if(WIN32)
        set_tests_properties(guest_posix_file PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libScePosixForWebKit>")
    endif()
endif()
